# Generated by Django 5.2.8 on 2025-11-28 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222)),
                ('surname', models.CharField(max_length=222)),
                ('information', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['name', 'surname'], name='names_index')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222)),
                ('surname', models.CharField(max_length=222)),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('is_married', models.BooleanField()),
                ('city', models.CharField(max_length=222)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main.teacher')),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='main_studen_name_d24c58_idx'), models.Index(fields=['surname'], name='main_studen_surname_307540_idx'), models.Index(fields=['city'], name='main_studen_city_fc36fe_idx'), models.Index(fields=['created_at'], name='main_studen_created_52588c_idx')],
            },
        ),
    ]
